qanda/urls.py
from django.urls import path

from .views import (AskQuestionView,
                    QuestionDetailView,
                    CreateAnswerView,
                    UpdateAnswerAcceptance,
                    DailyQuestionList,
                    TodaysQuestionList,
                    SearchView, )

app_name = 'qanda'
urlpatterns = [
    path('ask', AskQuestionView.as_view(), name='ask'),
    path('q/search', SearchView.as_view(), name='question_search'),
    path('q/<int:pk>', QuestionDetailView.as_view(), name='question_detail'),
    path('q/<int:pk>/answer', CreateAnswerView.as_view(), name='answer_question'),
    path('a/<int:pk>/accept', UpdateAnswerAcceptance.as_view(), name='update_answer_acceptance'),
    path('daily/<int:year>/<int:month>/<int:day>/', DailyQuestionList.as_view(), name='daily_questions'),

    path('', TodaysQuestionList.as_view(), name='index'),

]

user/urls.py
from django.urls import path

from django.contrib.auth.views import (LoginView,
                                       LogoutView)
from .views import RegisterView

app_name = 'user'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register')
]

qanda/models.py
from django.conf import settings
from django.db import models
from django.urls.base import reverse
from .service import elasticsearch


class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qanda:question_detail',
                       kwargs={'pk': self.id})

    def can_accept_answers(self, user):
        return user == self.user

    def as_elasticsearch_dict(self):
        return {
            '_id': self.id,
            '_type': 'doc',
            'text': '{}\n{}'.format(self.title, self.question),
            'question_body': self.question,
            'title': self.title,
            'id': self.id,
            'created': self.created
        }

    def save(self,
             force_insert=False,
             force_update=False,
             using=None,
             update_fields=None):
        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)
        elasticsearch.upsert(self)


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question,
                                 on_delete=models.CASCADE)
    accepted = models.BooleanField(blank=True, default=False)

    class Meta:
        ordering = ('-created',)

qanda/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import (Question,
                     Answer)


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=get_user_model().objects.all(),
                                  disabled=True)

    class Meta:
        model = Question
        fields = ['title', 'question', 'user', ]


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    question = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Question.objects.all(),
        disabled=True
    )

    class Meta:
        model = Answer
        fields = ['answer', 'user', 'question', ]


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

    class Meta:
        model = Answer
        fields = ['accepted', ]

qanda/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls.base import reverse
from django.utils import timezone
from django.views.generic import (CreateView,
                                  DetailView,
                                  UpdateView, )
from django.views.generic import (DayArchiveView,
                                  RedirectView,
                                  TemplateView, )

from qanda.service.elasticsearch import search_for_question
from .forms import (QuestionForm,
                    AnswerForm,
                    AnswerAcceptanceForm)
from .models import (Question,
                     Answer, )


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'qanda/ask.html'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')

        if action == 'SAVE':
            return super().form_valid(form)

        elif action == 'PREVIEW':
            preview = Question(
                question=form.cleaned_data['question'],
                title=form.cleaned_data['title'])
            ctx = super().get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class QuestionDetailView(DetailView):
    model = Question

    ACCEPT_FORM = AnswerAcceptanceForm(initial={
        'accepted': True
    })
    REJECT_FORM = AnswerAcceptanceForm(initial={
        'accepted': False
    })

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'answer_form': AnswerForm(initial={
                'user': self.request.user.id,
                'question': self.object.id,
            })
        })

        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                'accept_form': self.ACCEPT_FORM,
                'reject_form': self.REJECT_FORM,
            })

        return ctx


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = 'qanda/create_answer.html'

    def get_initial(self):
        return {
            'question': self.get_question().id,
            'user': self.request.user.id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):

        action = self.request.POST.get('action')

        if action == 'SAVE':

            return super().form_valid(form)

        elif action == 'PREVIEW':
            preview = Question(question=form.cleaned_data['question'],
                               title=form.cleaned_data['question'].title)
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs['pk'])


class UpdateAnswerAcceptance(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(to=self.object.question.get_absolute_url())


class DailyQuestionList(DayArchiveView):
    queryset = Question.objects.all()
    date_field = 'created'
    month_format = '%m'
    allow_empty = True


class TodaysQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse('qanda:daily_questions',
                       kwargs={
                           'day': today.day,
                           'month': today.month,
                           'year': today.year
                       })


class SearchView(TemplateView):
    template_name = 'qanda/search.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('q', None)
        ctx = super().get_context_data(query=query, **kwargs)

        if query:
            results = search_for_question(query)
            ctx['hits'] = results

        return ctx

templates/qanda/common/display_question.html
{% load markdownify %}

<div class="question">
    <div class="meta col-sm-12">
        <h1>{{ question.title }}</h1>
        Asked by {{ question.user }} on {{ question.created }}
    </div>

    <div class="body col-sm-12">
        {{ question.question|markdownify }}
    </div>
</div>

templates/qanda/common/list_answers.html
{% load markdownify %}
<h3>Answers</h3>

<ul class="answer row">
    {% for answer in question.answer_set.all %}
        <li class="answer row">
            <div class="col-sm-3 col-md-2 text-center">
                {% if answer.accepted %}
                    <span class="badge badge-pill badge-success">
                Accepted
            </span>
                {% endif %}

                {% if answer.accepted and reject_form %}
                    <form method="post"
                          action="{% url 'qanda:update_answer_acceptance' pk=answer.id %}">

                        {% csrf_token %}
                        {{ reject_form }}
                        <button type="submit" class="btn btn-link">
                            <i class="fa fa-times" aria-hidden="true"></i>
                            Reject
                        </button>

                    </form>

                {% elif accept_form %}
                    <form method="post" action="{% url 'qanda:update_answer_acceptance' pk=answer.id %}">
                        {% csrf_token %}
                        {{ accept_form }}
                        <button type="submit" class="btn btn-link" title="Accept answer">
                            <i class="fa fa-check-circle" aria-hidden="true"></i>
                            Accept
                        </button>
                    </form>
                {% endif %}
            </div>
            <div class="col-sm-9 col-md-10">
                <div class="body">{{ answer.answer|markdownify }}</div>
                <div class="meta font-weight-light">
                    Answered by {{ answer.user }} on {{ answer.created }}
                </div>
            </div>
        </li>
    {% empty %}
        <li class="answer">No answer yet!</li>
    {% endfor %}
</ul>

templates/qanda/common/post_answer.html
{% load crispy_forms_tags %}

<div class="col-sm-12">
    <h3>Post your answer</h3>

    <form method="post" action="{% url 'qanda:answer_question' pk=question.id %}">
        {{ answer_form | crispy }}
        {% csrf_token %}
        <button class="btn btn-primary" type="submit" name="action" value="PREVIEW">Preview
        </button>
        <button class="btn btn-primary" type="submit" name="action" value="SAVE">Answer
        </button>

    </form>
</div>