qanda/urls.py
from django.urls import path

from .views import (AskQuestionView,
                    QuestionDetailView,
                    CreateAnswerView,
                    UpdateAnswerAcceptance,
                    DailyQuestionList,
                    TodaysQuestionList,
                    SearchView, )

app_name = 'qanda'
urlpatterns = [
    path('ask', AskQuestionView.as_view(), name='ask'),
    path('q/search', SearchView.as_view(), name='question_search'),
    path('q/<int:pk>', QuestionDetailView.as_view(), name='question_detail'),
    path('q/<int:pk>/answer', CreateAnswerView.as_view(), name='answer_question'),
    path('a/<int:pk>/accept', UpdateAnswerAcceptance.as_view(), name='update_answer_acceptance'),
    path('daily/<int:year>/<int:month>/<int:day>/', DailyQuestionList.as_view(), name='daily_questions'),

    path('', TodaysQuestionList.as_view(), name='index'),

]

user/urls.py
from django.urls import path

from django.contrib.auth.views import (LoginView,
                                       LogoutView)
from .views import RegisterView

app_name = 'user'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Answer-ly{% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          rel="stylesheet">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet">

    <link rel="stylesheet" href="{% static 'base.css' %}">


</head>

<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Answer-ly</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'qanda:ask' %}">Ask</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'qanda:index' %}">Today's Questions</a>
            </li>



            {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}">Login</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                </li>
            {% endif %}

            <li class="nav-item">
                <form class="form-inline"
                      action="{% url 'qanda:question_search' %}"
                      method="get">

                    <input class="form-control mr-sm-2" type="search"
                           name="q" placeholder="Search">

                    <button class="btn btn-outline-primary my-2 my-sm-0"
                            type="submit">Search
                    </button>
                </form>
            </li>


        </ul>
    </div>
</nav>

<div class="container">
    {% block body %}
    {% endblock %}
</div>

</body>

</html>